### ISSUE TITLE
Canvas rendering?

### ISSUE THREAD

**Issue by mbostock** [d3/d3-axis#2]
It wouldn’t be as configurable as SVG rendering, since you wouldn’t be able to apply a stylesheet or perform post-selection; and I definitely wouldn’t want to open the door to a million configuration options. (You can always overlay SVG on top of Canvas if you want to customize the appearance.)

**Comment by mbostock** [comment]
Would probably be implemented as *axis*(*context*) rather than *axis*(*selection*).

**Comment by mbostock** [comment]
Punting on this for now. It would be feature-poor compared to SVG (no transitions, no stylesheets, no post-selection), and thus probably better to think about as a separate module.

**Comment by curran** [comment]
I came across this nice example by @syntagmatic that shows how SVG axes can be used as a layer on top of a visualization rendered on Canvas - [Canvas Parallel Coordinates](http://bl.ocks.org/syntagmatic/2409451). This is a nice approach to leverage both SVG and Canvas, and I think it justifies only providing an SVG API for axes.

**Comment by mbostock** [comment]
Yep, totally.
