### ISSUE TITLE
d3 shape like API

### ISSUE THREAD

**Issue by clozr** [d3/d3-axis#20]
I am trying to integrate d3 axis into a react-native application.
d3 shape API is quite good in the sense that it gives back the raw path data which could be directly used with react-native ART api.
However d3-axis doesn't have similar isolation. it relies on knowledge of DOM to setup the path correctly. It would be nice to have an API to get those axis, ticks and labels path directly so that it can be used with any compatible rendering methods.

**Comment by mbostock** [comment]
No plans to implement this. You can use d3-scale (and d3.ticks from d3-array) if you want to roll your own axes without using SVG.
