### ISSUE TITLE
Ticks transition sometimes produces console errors when used with tickValues

### ISSUE THREAD

**Issue by kamiua** [d3/d3-axis#30]
There is issue we have which probably is related to [#24].
[Here](https://bl.ocks.org/kamiua/6379dfb73a6dbe3cd2609d6657b53270) is example for reproduction.

**Comment by mbostock** [comment]
You are specifying tick values that are not defined in your scale’s domain. For example:

```js
domain = [316, 225, 392, 377, 336, 295, 382, 270, 391, 224, 251, 319, 207, 204, 383]
tickValues = [363, 276, 249]
```

Ordinal scales (including band and point scales) are only defined on their domain, so it’s not possible to render tick values outside of the domain.
