### ISSUE TITLE
Y-axis defect at RTL mode

### ISSUE THREAD

**Issue by Ashamandi** [d3/d3-axis#31]
When I tried to add **dir="rtl"** in body tag at this example [Line with Missing Data](https://bl.ocks.org/mbostock/0533f44f2cfabecc5e3a)

**hint:** I replace "https://d3js.org/d3.v4.js" with "//d3js.org/d3.v4.0.0-alpha.4.min.js"-

The following error appears:

![y-axis_defect](https://cloud.githubusercontent.com/assets/17547411/23606797/f3e4f4f0-026a-11e7-8f86-e2f4b63ce6f7.jpg)

**Comment by mbostock** [comment]
This is expected. If you add `dir="rtl"`, you’ll need to restyle your axis as appropriate since the default tick text-anchor for a left or right axis will no longer be correct. For example, you may need to add the following style:

```css
.axis--y {
  text-anchor: start;
}
```

**Comment by HarelM** [comment]
@mbostock I have this issue too.
my solution was to set the everything to `ltr` which I don't think is a great workaround.
Not supporting this out-of-the-box requires every developer that needs RTL support to know this and take it into account when using d3.
I think that it should be build-in in this library.
Please consider re-opening this issue.
