### ISSUE TITLE
Feasibility of returning html string

### ISSUE THREAD

**Issue by GabeMedrash** [d3/d3-axis#5]
Would it be feasible to optionally *just* return the html string instead of rendering directly to the DOM (or otherwise depending on the DOM at all)?

**Comment by mbostock** [comment]
Not really. That would be a completely different implementation. But you could maybe use JSDOM and then serialize the result, or if in a browser, you could render to a detached DOM node and then serialize that.

(Also, it’s mostly SVG, not HTML.)
