### ISSUE TITLE
Render in vanilla HTML?

### ISSUE THREAD

**Issue by IPWright83** [d3/d3-axis#58]
I want to propose the idea of rendering axis in pure HTML (rather than SVG).

SVG is great for it's power, but I've found generally text manipulation/styling is generally much more difficult. With regular HTML I believe we could leverage things such as auto-truncation of long labels in CSS, simpler sizing of fonts etc.

Be interested to know thoughts on this (obviously would be a re-implementation of the renderer). I was taking a look at a Parallel Co-ordinates chart at the time and thinking there's quite a bit of work to be done with scaling and contrast to make the chart more accessible.

**Comment by mbostock** [comment]
I have no interest in writing an HTML version of the axis component, sorry. You are welcome to fork this repository and take a crack it yourself. Good luck!

**Comment by IPWright83** [comment]
@mbostock No problem - I thought that might be the case. I wonder, have you had many issues with font size/text length in examples you've built? Or have you managed to avoid this with bespoke charts? 

I've often found in re-usable charts I've hit this problem, and in this case using a plug-in I'm left with little control other than selecting the DOM after generation and modifying, which is a little frustrating.
