### ISSUE TITLE
Right-align tick text in axisRight() ?

### ISSUE THREAD

**Issue by tippmar** [d3/d3-axis#59]
Is there a way to right-align the tick text when creating a right axis via `axisRight()`?  

I'm currently rendering a right axis on my graph like so:
```function renderGapAxes(root: RenderRegion) {
  root
    .attr("class", "y gap-axis")
    .attr("margin-top", margin.top)
    .attr("transform", `translate(${width})`)
    .call(
      d3.axisRight(barYScale)
        .tickPadding(-1),
    );
}
```
and I get results like so: 
![image](https://user-images.githubusercontent.com/38259468/64440994-9f6c7a80-d092-11e9-8281-2acd3c6d21e5.png)
but I want the numbers to be right-aligned.

**Comment by mbostock** [comment]
You can use d3.axisLeft if you want right-aligned ticks. Sometimes I use an axisRight on the left side of the plot, as in this [contour plot example](https://observablehq.com/@d3/contours).

Alternatively, you can select the elements generated by the axis and modify them however you like, as in the [styled axes example](https://observablehq.com/@d3/styled-axes).
