### ISSUE TITLE
not able to add custom attributes to the axis

### ISSUE THREAD

**Issue by shivasai09** [d3/d3-axis#73]
we now that using `axisBottom` or `axisRight` or any other axis making function, we get the below HTML,
![image](https://user-images.githubusercontent.com/33802398/98516776-efe0f880-2292-11eb-83cd-80a3eaa3e8cf.png)

**but my concern is how to add custom attributes to the `<line>` or `<text>` elements.**

I need this to increase the accessibility for our product. if it is possible to add custom attributes to `<line>` or `<text>`, then i would like to add the `aria-*` attributes to it so, that my screen reader will be able to give more descriptive information. 

can any one help me how to achieve this.?

Thanks,
Siva

**Comment by Fil** [comment]
You can call a function after applying an axis, see https://observablehq.com/@d3/connected-scatterplot#xAxis for an example.
