### ISSUE TITLE
Offset ticks and domain path by a half-pixel?

### ISSUE THREAD

**Issue by mbostock** [d3/d3-axis#8]
Safari often botches shape-rendering: crispEdges, drawing a two-pixel-wide line even though the stroke-width is one pixel. Also, in the common case where the coordinates are rounded, using a half-pixel offset should produce crisp edges even without shape-rendering.

I think we should use zero-based indexing for coordinates, such that *y* = 0 means the topmost pixel and *x* = 0 means the leftmost pixel, and therefore offsetting by +0.5 (not -0.5) in both *x* and *y*.

**Comment by curran** [comment]
I have also noticed this behavior and been frustrated by it. I appreciate that you're working on this. Sounds like a great solution to me!
