### ISSUE TITLE
d3-axis does not update SVG attributes when switching between axis orientations

### ISSUE THREAD

**Issue by lgdevlop** [d3/d3-axis#89]
We need to update some attributes when changing between axis orientations so the line and text scale do not overlap.

Link to reproduce this behavior.

https://codesandbox.io/s/proud-wave-q468bd

**Comment by mbostock** [comment]
This is expressly disallowed in the [README](https://github.com/d3/d3-axis/blob/main/README.md#api-reference):

> The orientation of an axis is fixed; to change the orientation, remove the old axis and create a new axis.

**Comment by lgdevlop** [comment]
Good to know; thanks!
I'm closing this issue.

**Comment by mbostock** [comment]
Thanks. I appreciate the contribution nonetheless. It’s a reasonable feature request but for now I’d just prefer to keep the code simple! 🙏
